server:
  port: 0

oidc:
  client-id: sb
  client-secret: sb
  base-url: http://localhost:9889

spring:
  security:
    oauth2:
      client:
        registration:
          mine:
            provider: oidc
            client-id: sb
            client-secret: sb
            scope: openid,email,profile
        provider:
          oidc:
            issuer-uri: http://localhost:9889
